### ISSUE TITLE
Using !tele mea command causes error 2003 "Unable to read data"

### ISSUE THREAD

**Issue by LadyLux** [HomepointXI/Issues#1]
**Date & Time**: March 10th, 9:57 AM CST

**Client Version (use `/ver` in game):** 30180203_1

**Character Name:** Ladylux

**Nation:** Bastok

**Job(level)/Sub Job(level):** Thief(99)/Dancer(49)

**NPC or Monster or item Name:** N/A

**Zone name:** Tahrongi Canyon

**Coordinates (use `!where`):** Crag of Mea

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** Yes

**Steps to reproduce:** Using !tele mea command

**Any additional information:**  Reason to believe it is a corrupt file, have been able to replicate this multiple times on each of my characters.

**Comment by EpicTaru** [comment]
Per our convo via DM you ran the POL file check. Files were found but issue persisted. You then ran the windows 10 disk scanner with negative results. You ran pol file check again, which again produced corrupt files. At that point you did a full uninstall and reinstall of ffxi.

Please update with your findings from this point on and also please correct anything that I said if it was in error.

**Comment by Devolnu** [comment]
Having the same issue. Teleport and walking into that zone crashes with error: FFXI-2003. I am currently checking files to update. i do have an older version. will let you know if this fixes it.

**Comment by Devolnu** [comment]
update version now is ver.30180306_2 i had the version ver.30171004_1  getting the same error after updating FFXI-2003 when zoning into Tahrongi Canyon. The issue is the zone not the actual teleport.

**Comment by EclipseSin** [comment]
Date & Time: March 13th, 8:48 PM EST

Client Version (use /ver in game): 30171103_1

Character Name: Chiyorin

Nation: San d'Oria

Job(level)/Sub Job(level): Dancer(99)/Thief(49)

NPC or Monster or item Name: N/A

Zone name: Tahrongi Canyon

Coordinates (use !where): Crag of Mea

Item tool link (for items issues only):

Multi-boxing? (multiple clients on same connection): No

Steps to reproduce: Using !tele mea command 

Works as intended (assumed). Causes casting animation and teleport sound then teleport to Tahrongi Canyon Gate Crystal (proper coordinates). No Error. 

Without crag crystal !tele does not work as also assumed it is intended. 

Obtaining Crag of Mea Gate Crystal causes the message "Obtained 354 Gil" and "Your Chocobo refuses to partake of the . ". This is probably just a string id mismatch.

![chiyorin_2018 03 14_003326](https://user-images.githubusercontent.com/4019608/37383627-33f3c7b2-2720-11e8-8c75-25d6abd94ae1.png)
 This was a fresh install during the free login campaign On November 10th, 2017. I have not updated since then.

**Comment by nfaletra** [comment]
That last post is just a Text ID being off. 354 is actually the key item ID but it's telling the client to display the wrong message because of version mismatch. Check your Key Items and it should be there. Not related to the issue originally described.

**Comment by nfaletra** [comment]
Possibly related to a corrupt file. Cannot reproduce on new version.
