### ISSUE TITLE
2 of my characters cannot progress past ancient vows CoP mission

### ISSUE THREAD

**Issue by lonleyhero** [HomepointXI/Issues#172]
**Date & Time**: 
ive actually done the bcnm for ancient vows a couple times for them most recently last night around 9pm ish est

**Client Version (use `/ver` in game):**

30180801_2

**Character Name:**
pocketmage, and lonelyhero

**Discord Name (if different from in game):**

lonelyhero#6721

**Nation:**

bastok

**Job(level)/Sub Job(level):**
rdm99/whm49 and thf99/dnc49

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

this most recent attempt yes

**Steps to reproduce:**

**Any additional information:**
Ive completed the bcnm fight for ancient vows with both characters a couple times now and they get sent out to miseraux coast as if they've beaten it already but the mission stays set to ancient vows and i cannot trigger the cutscene in port bastok at the airship dock no matter how many times i zone

**Comment by EpicTaru** [comment]
Checked variables on both characters.  Variable PromathiaStatus == 2 (instead of 0) for both characters.  Variable VowsDone == 0 (instead of 1) for both characters.  Player indicated that both characters were in the same battle last night, @spectre99 was also present to assist last night.  

Presence of both characters in the battle at same time probably caused the variables to not update.

Spectre and I assisted with the BCNM fights again, once each for both characters (with no other characters logged in), after which the variables for both characters updated correctly.
