### ISSUE TITLE
NPC Issue: Antonia non-responsive

### ISSUE THREAD

**Issue by neoffxi** [HomepointXI/Issues#174]
**Date & Time**: 
08/20/2018 12:33PM

**Client Version (use `/ver` in game):**
30180801_2

**Character Name:**
Neomorpheus

**Discord Name (if different from in game):**
Neo

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
PLD 99 / WAR 49

**NPC or Monster or item Name:**
Antonia -- Arasy gear NPC

**Zone name:** 
Upper Jeuno (H-8)

**Coordinates (use `!where`):**
n/a

**Item tool link (for items issues only):**
n/a

**Multi-boxing? (multiple clients on same connection):**
n/a

**Steps to reproduce:**
1. The NPC, Antonia, doesn't respond when you talk to her.
2. No response were given even after repeated interactions with the NPC.

**Any additional information:**
This is the NPC that sells Arasy gear. Lumb was asking about it few days ago too, but it seems the NPC was disabled?

There's only really two decent Arasy pieces which are the PUP animator and SMN ammo. Unlike the weapons that have recipes and can be crafted, both the animator and ammo can only be bought from the said NPC.

**Comment by Heepster03** [comment]
Arasy stuff has to be crafted. If the recipes are missing then they can be added at a later date. But to answer the question, yes her shop is disabled.

**Comment by nfaletra** [comment]
Because Arasy Sachet and Animator Z do not have recipes on retail, Antonia has been re-enabled and will be selling ONLY these two items.

These items can be crafted into better versions. Animator Z uses Synergy on retail. Custom synths for the synergy recipes have been added requiring the same materials and crafting skill levels.

Other Arasy weapons still need to be crafted.
