### ISSUE TITLE
Mission 2-3 (can't trade Mythril Sand to Savae)

### ISSUE THREAD

**Issue by AFMike32** [HomepointXI/Issues#176]
**Date & Time**: 
19 Aug 2018. 1730 Japanese time.

**Client Version (use `/ver` in game):**

30180801_2
**Character Name:**
Whitehawk

**Discord Name (if different from in game):**

AFMike

**Nation:**

Sandy

**Job(level)/Sub Job(level):**
Rdm57/Blm28

**NPC or Monster or item Name:**

Savae E paleade

**Zone name:** 

Metalworks

**Coordinates (use `!where`):**

Embassy

**Item tool link (for items issues only):**

Trying to trade Onz of Mythril sand.

**Multi-boxing? (multiple clients on same connection):**

Yes, Blackhawk is my first character, Whitehawk is my sec character

**Steps to reproduce:**

**Any additional information:**

Trying to trade her sand to more on in the quest. I have done every step.

**Comment by EpicTaru** [comment]
Player reported that he had both characters (Whitehawk and Blackhawk) online and doing the steps of this mission together at the same time.

Both characters correctly started Sandy Mission 2-3 (Journey Abroad), choosing the Bastok > Windurst path.  

Both characters correctly progressed thru the steps of the mission path thru the part of turning the Mine Gravel into Mythril Sand.  Both characters then returned to Savae E Paleade at the same time.  

Blackhawk traded the Mythril Sand to Savae and successfully completed that portion of the pathline.  His MissionStatus variable correctly updated from 5 to 6.  

It is my assumption that due to also being online at the same time, the **MissionStatus variable of Whitehawk was also, at that time, incorrectly updated from 5 to 0.**

Attempts to have Whitehawk talk to all of the NPCs (working backwards from Savae all the way back to Halver were not met with success in getting the same event/CS that the character had with that NPC previously.

**Comment by AFMike32** [comment]
It is now fixed and I am able to trade the Sand to the NPC. Problem is solved.

**Comment by EpicTaru** [comment]
Wonderful to hear! Closing ticket.
