### ISSUE TITLE
Mission 2-3 Sandy Mythril sand isnt working

### ISSUE THREAD

**Issue by tifya** [HomepointXI/Issues#220]
**Date & Time**: 
2018-10-01

**Client Version (use `/ver` in game):**
last 3018904

**Character Name:**
Nashirok

**Discord Name (if different from in game):**
Tifya

**Nation:**
Sandy

**Job(level)/Sub Job(level):**
Drg99

**NPC or Monster or item Name:**
Savae E pleade

**Zone name:** 
Metal work

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
i did zone and quit game reopen and done every step back nothing happen i got mythril sand in pocket twice i drop the other one before getting the new one again and its isnt working still . i did retalk to all of them twice again. my quest says mythil too .

**Any additional information:**

**Comment by tifya** [comment]
multiboxing i did take time to pur all at 30 fps and did them 1 by one to be sure

**Comment by EpicTaru** [comment]
Player reported that he had multiple characters (Tif, Tifya, and Nashirok) online and doing the steps of this mission together at the same time.

Both characters correctly started Sandy Mission 2-3 (Journey Abroad), choosing the Bastok > Windurst path.

All characters correctly progressed thru the steps of the mission path including the part of speaking to Grohm.  At this point in the mission, the value of the **MissionStatus** variable should have updated to a value of **5** for all 3 of the characters.  It correctly did so for Tif and Tifya but **incorrectly set the value of the **MissionStatus** variable to **0** on _Nashirok_.

Since the script for the **Mythril Seam** and the scripts for the **Refiner** in Palborough Mines don't do a check of the **MissionStatus** variable, all 3 characters were able to successfully obtain the Mine Gravel (ItemID 597) (and subsequently turn the sand into the Mythril Sand (ItemID 599)).

Upon returning to Metalworks and talking with Savae E Paleade, due to the **MissionStatus** variable having a value of **0** (where it needed to be a **5**), this caused the inability of Nashirok to be unable to turn the Mythril Sand in and complete this part of the mission to progress forward. Both Tif and Tifya were able to successfully trade the Mythril Sand in.

Attempts to have Nashirok talk to all of the NPCs (working backwards from Savae all the way back to Halver and especially Grohm) were not met with success in getting the same event/CS that the character had with that NPC previously.  The value of the **MissionStatus** variable did not change from **0**.

**Comment by Jessland86** [comment]
Set MissionStatus to 5 on Nash.
