### ISSUE TITLE
I broke the rules and ended up in jail

### ISSUE THREAD

**Issue by Zelkaden** [HomepointXI/Issues#23]
**Date & Time**: 
4/12/18 8:00 am

**Client Version (use `/ver` in game):**

Version 30180329_1

**Character Name:**
Zelkaden

**Discord Name (if different from in game):**

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
pup 9/ war 4

**NPC or Monster or item Name:**

**Zone name:** 
Jail

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
no

**Steps to reproduce:**
i used /debuff

**Any additional information:**
I should of read the rules before assuming it was the same as the last server.

**Comment by EpicTaru** [comment]
@Zelkaden This happens from using tools or addons that try to strip off status effects that you normally cannot.

Each time that happens the code will re-jail, even if you are already in jail. Please disable any such tools and remove them and any Windower or Ashita scripts or macros that would attempt to automatically remove such effects (like weakness) so that you don't auto-jail yourself again, and you will be released at the earliest convenience of a GM or admin. Hopefully you will never see yourself in jail again.

tl;dr
A GM or Admin will be with you when one gets the chance to.

**Comment by EpicTaru** [comment]
OK, are you online and logged in the game on the jailed character?

**Comment by Zelkaden** [comment]
yes i am logged in as Zelkaden now

**Comment by EpicTaru** [comment]
Released @1330 CST 04/12/2018
