### ISSUE TITLE
Job ability timers

### ISSUE THREAD

**Issue by stevomatic** [HomepointXI/Issues#31]
**Date & Time**: 
708pm est 4/21/18

**Client Version (use `/ver` in game):**
30180203_1

**Character Name:**
agnes gurgitator langridge growler

**Discord Name (if different from in game):**

**Nation:**
bastok

**Job(level)/Sub Job(level):**
blurdm rdmwhm thfdnc pldwar

**NPC or Monster or item Name:**
soaring

**Zone name:** 
maquette abdhaljs legion

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**
Noticed the majority of my JA timers are on a 10+ hour cooldown after doing Hall of Im, not sure what triggered it and I didn't notice till after I exited. Also I use stock retail XI macros, and I noticed inside that anything with a /wait wasn't working correctly. For instance if I had a /wait 4 in there it would be more like /wait 16

**Any additional information:**

**Comment by Jessland86** [comment]
Reset players recast timers. Investigating root cause at the moment. Advised to let me know if it happened again.

**Comment by nfaletra** [comment]
Can’t get in game right now, but I was farming a paladin testimony for my alt. Went to Beadeaux, had the alt nexus cape to me, got the drip, all without issue. Instant warped both characters back to Jeuno and all recast timers (job abilities, items, etc.) shot up to 12 hours.

Was immediately noticeable because I use Recast on windowed and all of the graphics popped up on my screen.

I thought it was just the addon freaking out but confirmed the issue in ffxi menus, as well.

**Comment by nfaletra** [comment]
Relevant characters are Autkastx and Bryer.

**Comment by nfaletra** [comment]
I also popped and killed Charybdis. During the fight the timers on my buffs and debuffs (the ones built into the game, not an add-on) disappeared and the icons started flashing like they were about to wear, but they lasted the appropriate amount of time.
