### ISSUE TITLE
Burtgang (85) - Atonement cap at 990 damage

### ISSUE THREAD

**Issue by munkee128** [HomepointXI/Issues#343]
**Date & Time**: 
1/9/2019 ; 9:35 AM (PST)

**Client Version (use `/ver` in game):**
30181205_0

**Character Name:**
Munkee

**Discord Name (if different from in game):**
Munkee128

**Nation:**
NA

**Job(level)/Sub Job(level):**
PLD99/WAR49

**NPC or Monster or item Name:**
Burtgang (85)

**Zone name:** 
NA

**Coordinates (use `!where`):**
NA

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Yes

**Steps to reproduce:**
Atonement WS is capped at 990 no matter how much hate/enmity is on my character. 

**Any additional information:**
Similar issue as Issue #143

**Comment by Jessland86** [comment]
This is intentional. With the implementation of weapon skill unlocks, as well as an overall review of what LegionDark's atonement buff was supposed to do, the buff was no longer was working the way it was intended to work. TP move cooldowns on mobs were implemented so you can bring actual DD's to fight things. As such, Atonement was put back to retail accuracy.

**Comment by munkee128** [comment]
Ah, gotcha. Thank you.
