### ISSUE TITLE
Pso'Xja Pass

### ISSUE THREAD

**Issue by valkus8712** [HomepointXI/Issues#353]
**Date & Time**:  2/18/2019  1:26PM CST

**Client Version (use `/ver` in game):**   30181205|_0

**Character Name:** Olgaflow

**Discord Name (if different from in game):**  Kapiku

**Nation:** Sandoria

**Job(level)/Sub Job(level):** rdm99/whm49

**NPC or Monster or item Name:**  NPC "Ghebi Damomohe" 

**Zone name:**  Lower jueno neptunes spire

**Coordinates (use `!where`):**

**Item tool link (for items issues only):** grey chip

**Multi-boxing? (multiple clients on same connection):** no

**Steps to reproduce:** get chip talk to npc

**Any additional information:** the npc will not let me trade her any color chip for my psoxja pass in return i am on the right quest and have gotten the correct cutscenese my friend had no problem so im not sure whats going on

**Comment by Heepster03** [comment]
Multiboxing can lead to some serious variable issues.

**Comment by EpicTaru** [comment]
Player is fairly certain that he wasn't multiboxing (player said that he wasn't sure what the Multiboxing question on the above form was referring to) when he interacted with Ghebi Damomohe but the player's **PXPassGetGems** is not correctly updating to the needed value of 1 no matter how many times Olgaflow talks to Ghebi, no matter how much Olgaflow begs and pleads and throws chips at **#GhebiTheMeanie!!!**

@Heepster03 or @Jessland86, please set the value of Olgaflow's **PXPassGetGems** variable to the needed value of **1**.  I have checked the variables on the character and that variable is the only one not updating correctly for this part of the mission.  The value of 1 for that variable will allow the player to trade the Gray Chip to Ghebi so that the mission can continue onward from that point.

**Comment by Heepster03** [comment]
This is a one-off. First time that I've ever heard someone having this issue. I reset my GM back to the beginning of this mission with all needed variables wiped and was able to still complete it with no issues. I reset the mission for him to start back at Monberaux again and see what Ghebi says this time.

**Comment by Heepster03** [comment]
Resolved by setting the variable manually. It still wouldn't do it.
