### ISSUE TITLE
All By Myself

### ISSUE THREAD

**Issue by TheToasterbox** [HomepointXI/Issues#355]
**Date & Time**: 
2/19/16

**Client Version (use `/ver` in game):**
30190202_0

**Character Name:**
Crosander

**Discord Name (if different from in game):**
TheToasterbox

**Nation:**
US

**Job(level)/Sub Job(level):**
All the jobs lowest is 10, highest is 16

**NPC or Monster or item Name:**
Ken

**Zone name:** 
Ken and Marin
Dengraf Wadi

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

no

**Steps to reproduce:**
Ken doesn't appear after I do the first part of the quest

**Any additional information:**

**Comment by EpicTaru** [comment]
Checked the scripts files and only found this block of code in Marin's script.

<code>function onTrigger(player,npc)
    player:startEvent(361);</code>

That block of code starts the CS for the beginning of the quest, the CS runs to completion but then nothing else occurs.  The quest isn't added to your Bastok current quests and you also do not get a CS upon zoning into Dangruf Wadi (which was also verified by the absence of code for such in the zone.lua file for Dangruf Wadi.

We'll keep this ticket open for the time being (unless Heep or Immo decide otherwise), hopefully someone will complete the coding for the remainder of this quest (but it may be a while as there are other escort quests/missions that are also not yet coded in DSP).

**Comment by Heepster03** [comment]
Closing as not worried about the Escort quests if they aren't implemented. Plenty of other ways to get XP and such :)
