### ISSUE TITLE
Cant continue chains of promathia 5-3

### ISSUE THREAD

**Issue by billyboy2020** [HomepointXI/Issues#403]
**Date & Time**: 
11:14pm est. 10/25/2019

**Client Version (use `/ver` in game):**

30190731_2

**Character Name:**

Billygirl, Lilbilly

**Discord Name (if different from in game):**

**Nation:**

Sandoria x2

**Job(level)/Sub Job(level):**

Thf,rdm 99

**NPC or Monster or item Name:**

Pheromicel

**Zone name:** 

Jeuno, rulude gardens

**Coordinates (use `!where`):**

G6

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**  dual box yes

Not able to get CS to continue to chp6 chains of promathia

**Steps to reproduce:**

Wish I knew

**Any additional information:** have talked to all previous npcs have completed all paths for 5-3. Not sure what else to do

**Comment by EpicTaru** [comment]
Please complete all of the fields listed and provide as much info as you can about where in chapter 6 you are such at.

**Comment by billyboy2020** [comment]
Lilbilly**€€

**Comment by EpicTaru** [comment]
The variables for both Billygirl and Lilbilly show that both characters are done with Ulmia's Path and Louverance's Path but are currently at the point in Tenzen's Path where you need to **examine the Avatar Gate**.  Please complete this and then the rest of Tenzen's Path. Once this is done, please attempt talking to Cid again.

Since you indicated that both characters were online while doing this path, that may have caused the variables of both of them to not correctly update.  Examining the Avatar Gate again should correctly update the variable.  Please respond to this ticket with the results of performing the above then completing the rest of Tenzen's Path for both characters.

![image](https://user-images.githubusercontent.com/26195580/67624583-02a79d00-f7f8-11e9-91d7-7d325de0b246.png)

![image](https://user-images.githubusercontent.com/26195580/67624793-17396480-f7fb-11e9-8d0b-25a3a30929ad.png)

**Comment by billyboy2020** [comment]
Ok I went back to avatar gate and received CS for both characters and following up by talking to did to complete three paths

**Comment by billyboy2020** [comment]
Cid*

**Comment by EpicTaru** [comment]
Good deal, glad to hear, closing this ticket. :)
