### ISSUE TITLE
My character cant log in

### ISSUE THREAD

**Issue by Blings** [HomepointXI/Issues#408]
**Date & Time**:  11/18/2019 7:25pm eatern time

**Client Version (use `/ver` in game):** version 30190328_2

**Character Name:** Bling

**Discord Name (if different from in game):** Bling

**Nation:** Windhurst

**Job(level)/Sub Job(level):** 84sch/rdm

**NPC or Monster or item Name:**

**Zone name:** maybe port jueno

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:** Just try logging in and screen dissappears and suddenly shuts

**Any additional information:** EpicTaru said that the problem appears to not be on my side bc i can log other toons. Also i created a secong character on Bling's account and it logged in fine.

**Comment by EpicTaru** [comment]
When did this issue start? What were you doing immediately before it started occurring?

**Comment by EpicTaru** [comment]
Also, please try and provide a screen shot of the screen just before the screen closes on you

**Comment by Blings** [comment]
I was in the moghouse in bastok mines and i tried to exit. The screen went black and said                         
 ".oOdownloding dataOo." in the bottom right corner and then froze.
I went to bed bc it was late. My stupid pitbull wouldnt stop jumping in my bed because it was thunderstorming so i moved to my living room couch. I woke up this morning and did some adulting as i do in the mornings. After that i tried to log Bling in before i started all the dishes that my lazy husband never rinses. The log in goes normal until it opens the final fantasy XI window. The window opens up black with ".oO Downloading data Oo." in the lower right corner. it instantly freezes and then everything shuts with no warning. Now without FFxi im going to be forced to do something lame like pinterest projects and my husband is going to leave me bc of all the old pallets ill end up piling in my garage. Old pallets that i think i can make into something cool but i just cant.

**Comment by EpicTaru** [comment]
This issue has been resolved. The issue was resolved by renaming the folder for the character (in the USER folder), meaning that all macros and settings for the character were lost (but they can at least once again log in and play as the character. 

Prior to the submittal of this ticket, the player and I had already attempted the following:

* Having the player un-stick the character via the website. 

* A reset of the character's POS. 

* A log-off of the character (by the player). 

* A log-off of the character (by my GM character). 

* Having the player fully reboot their computer, cable modem, and router. 

* Having the player log out all accounts and only log in the account having the issue.

None of the above methods resolved the issue. 

Also, for the record, the player provided me with their log in info, with which I was able to successfully and stably log in as the character and move/zone around. It was after this that we attempted the renaming of the folder for the character (as mentioned at the beginning of this comment). 

The player had indicated (on Discord) that just prior to them having this issue, they may have been experiencing lag (origin unknown). This lag may have corrupted something in the character's settings, causing this issue to occur.
