### ISSUE TITLE
Sandy Mission 2-1 Rescue Drill CS bad call

### ISSUE THREAD

**Issue by Guiness907** [HomepointXI/Issues#414]
**Date & Time**:  1/11/2020 10:53am Mountain

**Client Version (use `/ver` in game):** 30191204_1

**Character Name:** Guinness

**Discord Name (if different from in game):** Guiness

**Nation:** San d'Oria

**Job(level)/Sub Job(level):** 75THF/37DNC

**NPC or Monster or item Name:** Narvecaint, Displayed as Tayula

**Zone name:** La Theine Plateau

**Coordinates (use `!where`):** X:-291 Y:28 Z:142

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):** No

**Steps to reproduce:** Flag mission from gate guard.  Must speak to NPC above ravene, then speak to all NPCs before problem NPC.  Once you talk to NPC, CS is called then character cannot move, and menus cannot be opened until the CS is "skipped".

**Any additional information:**  GM was able to use !release to skip even and mission was then able to be completed.

**Comment by EpicTaru** [comment]
As player stated (this ticket is being done post issue for historical resolution notes), they were being frozen in a CS due to a call to an incorrect CS (most likely due to CS ID mismatches caused by version mismatch).  I first attempted to break the CS thru usage of the !bring command (no success) but then success forced the CS event to be skipped thru usage of the !release command.

Player was then able to proceed with the remainder of the mission all the way thru to completion.
