### ISSUE TITLE
Rank 2-3 Workaround

### ISSUE THREAD

**Issue by PunchdrunkXI** [HomepointXI/Issues#441]
**Date & Time**: 6.30PM Monday 27 July 2020

**Client Version (use `/ver` in game):** Version 30200604_0

**Character Name:**Punchdrunk, Curedrunk and Swipedrunk

**Discord Name (if different from in game):**Punchdrunk

**Nation:**Bastok

**Job(level)/Sub Job(level):**99Pld/49War

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**Yes

**Steps to reproduce:**

**Any additional information:**

**Comment by EpicTaru** [comment]
@PunchdrunkXI What part of 2-3 are you on?  Are you at the battlefield portion? If so, what battlefield are you set up to do the dragon/eye fight at?

**Comment by PunchdrunkXI** [comment]
punch is on 2-3 bcnm fight, just running other 2 chars to windy

**Comment by EpicTaru** [comment]
Where is Punch setup to do the fight at? Bastok? Sandy?

**Comment by PunchdrunkXI** [comment]
It will be the Windurst Dragon fight

**Comment by EpicTaru** [comment]
Excellent, please set up the other charas for there as well.  Atm, due to the version mismatches and the steps I have to take, the chances of succeeding at all if the fight is at Sandy are close to none.

Please respond here when you have all characters ready to enter the battle.  Don't enter it before I say to in game, please.

**Comment by PunchdrunkXI** [comment]
Understood and thank you

**Comment by EpicTaru** [comment]
The version mismatch between the server version and your client version will most likely cause the CS (that you'll see prior to entering the battlefield) to freeze.  I'll force you thru the CS you'll get frozen in.  The forcing of you thru the CS will cause your camera to be frozen at the entrance to the battlefield for the battle and because of that, I'm only requiring a defeat of one of the two mobs in the battle (more power to you if you manage to defeat both, lol).  

**You need to screenshot the message of you defeating one of the two mobs and then add that screenshot to this ticket** (you can then either die or leave the battle) and I'll fix your variables to be as if you completed the battle successfully.  You'll be able to continue the rest of the 2-3 mission storyline to complete it and obtain Rank 3.

If you don't freeze on the CS and are able to enter the battlefield normally, you'll need to defeat **both** mobs though.  I'll still verify that your variables and whatnot are correct after you've completed the battle to allow you to progress onward.

**Comment by PunchdrunkXI** [comment]
![Swipedrunk_2020 07 27_210127](https://user-images.githubusercontent.com/68868049/88586939-16b15100-d04d-11ea-9cd4-00274d24ec72.png)

**Comment by EpicTaru** [comment]
Verified deletion/addition of any KIs that needed to be done and adjustment of the MissionStatus/any other variables necessary according to the code for completion of the battle. Congrats!
