### ISSUE TITLE
Rank 2-3 Workaround

### ISSUE THREAD

**Issue by Skimmyson** [HomepointXI/Issues#442]
**Date & Time**: 07/27/2020

**Client Version (use `/ver` in game):**30200702_1

**Character Name:**Skimmy

**Discord Name (if different from in game):**Skimmyson71

**Nation:**Bastok

**Job(level)/Sub Job(level):**Mnk70/Dnc35

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**No

**Steps to reproduce:**

**Any additional information:**

**Comment by EpicTaru** [comment]
Skimmy, you're on the same client version as the server, please try and see if you can enter the battlefield for the 2-3 mission normally.

**Comment by Skimmyson** [comment]
oh ok

**Comment by EpicTaru** [comment]
**CORRECTION**, disregard what I just said, just updated your client version to what it actually is.

**Comment by EpicTaru** [comment]
What part of 2-3 are you on? Are you at the battlefield portion? If so, what battlefield are you set up to do the dragon/eye fight at?

**Comment by EpicTaru** [comment]
Please respond here when you have all characters ready to enter the battle. Don't enter it before I say to in game, please.

**Comment by EpicTaru** [comment]
The version mismatch between the server version and your client version will most likely cause the CS (that you'll see prior to entering the battlefield) to freeze. I'll force you thru the CS you'll get frozen in. The forcing of you thru the CS will cause your camera to be frozen at the entrance to the battlefield for the battle and because of that, I'm only requiring a defeat of one of the two mobs in the battle (more power to you if you manage to defeat both, lol).

**You need to screenshot the message of you defeating one of the two mobs and then add that screenshot to this ticket** (you can then either die or leave the battle) and I'll fix your variables to be as if you completed the battle successfully. You'll be able to continue the rest of the 2-3 mission storyline to complete it and obtain Rank 3.

If you don't freeze on the CS and are able to enter the battlefield normally, you'll need to defeat both mobs though. I'll still verify that your variables and whatnot are correct after you've completed the battle to allow you to progress onward.

**Comment by PunchdrunkXI** [comment]
![Swipedrunk_2020 07 27_210127](https://user-images.githubusercontent.com/68868049/88587069-46605900-d04d-11ea-947e-56e03a7d90ce.png)

**Comment by Skimmyson** [comment]
Thanks Punch

**Comment by EpicTaru** [comment]
Verified deletion/addition of any KIs that needed to be done and adjustment of the MissionStatus/any other variables necessary according to the code for completion of the battle. Congrats!
