### ISSUE TITLE
LET ME IN!!!! Mission 2-3 Workaround

### ISSUE THREAD

**Issue by boxghost7** [HomepointXI/Issues#445]
**Date & Time**: 
08/03/2020 11:43 EDT

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Jestr and Myblueballs

**Discord Name (if different from in game):**
Boxghost

**Nation:**
Bastok and Windurst

**Job(level)/Sub Job(level):**
Jestr NIN(99)/DNC(59)
Myblueballs RDM(99)/WHM(49)

**NPC or Monster or item Name:**
Searcher and Black Dragon

**Zone name:** 
Balga's Dais

**Coordinates (use `!where`):**
X:299 Y:-124 Z:344 (60)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Yes

**Steps to reproduce:**
- Click on burning circle named kupipi
- click on "The Rank 2 Final Mission"
- suffer through cutscene
- enjoy black screen

**Any additional information:**

**Comment by EpicTaru** [comment]
@boxghost7 Are all characters needing the workaround battle ready at the BCNM to enter the fight?

**Comment by boxghost7** [comment]
Yes, ready to rock and roll

**Comment by EpicTaru** [comment]
The version mismatch between the server version and your client version will most likely cause the CS (that you'll see prior to entering the battlefield) to freeze. I'll force you thru the CS you'll get frozen in. The forcing of you thru the CS will cause your camera to be frozen at the entrance to the battlefield for the battle and because of that, I'm only requiring a defeat of one of the two mobs in the battle (more power to you if you manage to defeat both, lol).

**You need to screenshot the message of you defeating one of the two mobs and then add that screenshot to this ticket** (you can then either die or leave the battle) and I'll fix your variables to be as if you completed the battle successfully. You'll be able to continue the rest of the 2-3 mission storyline to complete it and obtain Rank 3.

If you don't freeze on the CS and are able to enter the battlefield normally, you'll need to defeat both mobs though. I'll still verify that your variables and whatnot are correct after you've completed the battle to allow you to progress onward.

**Comment by boxghost7** [comment]
![20200803_121208](https://user-images.githubusercontent.com/60934733/89203524-b35e7c00-d582-11ea-98a4-a5047fb71aa4.jpg)

**Comment by EpicTaru** [comment]
Verified deletion/addition of any KIs that needed to be done and adjustment of the MissionStatus/any other variables necessary according to the code for completion of the battle. Congrats!
