### ISSUE TITLE
Rank 2-3 workaround

### ISSUE THREAD

**Issue by Oyasumimuzaki** [HomepointXI/Issues#455]
**Date & Time**: 9/10/2020

**Client Version (use `/ver` in game):**
30200731_2

**Character Name:** Oyasumi Muzaki

**Discord Name (if different from in game):** 

**Nation:** Bastok

**Job(level)/Sub Job(level):** thf 99/49 smn 93/46

**NPC or Monster or item Name:** 2-3 nation mission

**Zone name:** Balga's Dais

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

Yes

**Steps to reproduce:**

**Any additional information:**

**Comment by EpicTaru** [comment]
@Oyasumimuzaki where in the mission are you currently at? are you at the BCNM part?

Please also type `/ver` in game to display your client version.  Either respond with the client version or edit your ticket to include it in the relevant field.

**Comment by Oyasumimuzaki** [comment]
Bcnm version 30200731_2

**Comment by EpicTaru** [comment]
What part of the BCNM is giving you issues?  (this is why information in the listed fields of the ticket is necessary, lol)

**Comment by Oyasumimuzaki** [comment]
Beginning cs of BCNM froze both chars

**Comment by EpicTaru** [comment]
The version mismatch between the server version and your client version caused the CS to freeze. I'll force you thru the CS you're  frozen in. The forcing of you thru the CS will cause your camera to be frozen at the entrance to the battlefield for the battle and because of that, I'm only requiring a defeat of one of the two mobs in the battle (more power to you if you manage to defeat both, lol).

**You need to screenshot the message of you defeating one of the two mobs and then add that screenshot to this ticket** (you can then either die or leave the battle) and I'll fix your variables to be as if you completed the battle successfully. You'll be able to continue the rest of the 2-3 mission storyline to complete it and obtain Rank 3.

I'll verify verify that your variables and whatnot are correct after you've completed the battle to allow you to progress onward.

Knowing all this, are all of your characters ready to enter the battle? Please respond here.

**Comment by Oyasumimuzaki** [comment]
Yes

**Comment by Oyasumimuzaki** [comment]
![20200910_153009](https://user-images.githubusercontent.com/71097565/92791339-96377d00-f37a-11ea-8135-1c2922da1fc0.jpg)

**Comment by EpicTaru** [comment]
Give me a screenshot of your party list too, please, @Oyasumimuzaki

**Comment by Oyasumimuzaki** [comment]
![20200910_153219](https://user-images.githubusercontent.com/71097565/92791674-dc8cdc00-f37a-11ea-899f-b2103c2e8cd8.jpg)

**Comment by EpicTaru** [comment]
Verified deletion/addition of any KIs that needed to be done and adjustment of the MissionStatus/any other variables necessary according to the code for completion of the battle. Congrats!
