### ISSUE TITLE
Cutscene froze on Journey Abroad quest when entering Balga's Dais (Rank 2-3 Workaround)

### ISSUE THREAD

**Issue by K1SHIN4589** [HomepointXI/Issues#456]
**Date & Time**: 
09/16/20     4:44pm EST

**Client Version (use `/ver` in game):**
30200731_2

**Character Name:**
Makise

**Discord Name (if different from in game):**

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
SMN(70)/WHM(35)

**NPC or Monster or item Name:**
Searcher and Black Dragon

**Zone name:** 
Balga's Dais

**Coordinates (use `!where`):**
x:-139 y:55 z:-140 (67)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
Enter the burning circle in Balga's Dais for the Windurst part of the journey abroad quest, skip a few lines of dialogue and it will freeze.

**Any additional information:**
The timer still counts down

**Comment by EpicTaru** [comment]
The version mismatch between the server version and your client version caused the CS to freeze. I'll force you thru the CS you're  frozen in. The forcing of you thru the CS will cause your camera to be frozen at the entrance to the battlefield for the battle and because of that, I'm only requiring a defeat of one of the two mobs in the battle (more power to you if you manage to defeat both, lol).

**You need to screenshot the message of you defeating one of the two mobs and then add that screenshot to this ticket** (you can then either die or leave the battle) and I'll fix your variables to be as if you completed the battle successfully. You'll be able to continue the rest of the 2-3 mission storyline to complete it and obtain Rank 3.

I'll verify verify that your variables and whatnot are correct after you've completed the battle to allow you to progress onward.

Knowing all this, are all of your characters ready to enter the battle? Please respond here.

**Comment by K1SHIN4589** [comment]
I accept

**Comment by K1SHIN4589** [comment]
![img_1](https://user-images.githubusercontent.com/71410283/93396925-87533d80-f846-11ea-9096-2415580235cd.png)

**Comment by EpicTaru** [comment]
Verified deletion/addition of any KIs that needed to be done and adjustment of the MissionStatus/any other variables necessary according to the code for completion of the battle. Congrats!
