### ISSUE TITLE
Sandy Mission 2-3 CS to enter Fight Freeze (Rank 2-3 Workaround)

### ISSUE THREAD

**Issue by MVM1787** [HomepointXI/Issues#462]
**Date & Time**: Monday, September 28 9:55 AM

**Client Version (use `/ver` in game):**30200904_2

**Character Name:**Ligerzero

**Discord Name (if different from in game):**Ligerzer

**Nation:**Sandy

**Job(level)/Sub Job(level):**99 PUP/ 49 THF

**NPC or Monster or item Name:**

**Zone name:** Balga's Dias

**Coordinates (use `!where`):** X:299 Y:-124 Z:341 (62)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**None

**Steps to reproduce:** Use Dark Key to enter Sandy Mission 2-3 Fight with Dark Dragon and Ariman
![Ligerzero_2020 09 28_095246](https://user-images.githubusercontent.com/12943935/94463321-98b71680-0171-11eb-87e3-172d50ad7767.png)

**Any additional information:**

**Comment by EpicTaru** [comment]
The version mismatch between the server version and your client version caused the CS to freeze. I'll force you thru the CS you're  frozen in. The forcing of you thru the CS will cause your camera to be frozen at the entrance to the battlefield for the battle and because of that, I'm only requiring a defeat of one of the two mobs in the battle (more power to you if you manage to defeat both, lol).

**You need to screenshot the message of you defeating one of the two mobs and then add that screenshot to this ticket** (you can then either die or leave the battle) and I'll fix your variables to be as if you completed the battle successfully. You'll be able to continue the rest of the 2-3 mission storyline to complete it and obtain Rank 3.

I'll verify regardless that your variables and whatnot are correct after you've completed the battle to allow you to progress onward.

Knowing all this, are all of your characters ready to enter the battle? Please respond here.

**Comment by MVM1787** [comment]
Ready to go when you are

**Comment by MVM1787** [comment]
![Ligerzero_2020 09 28_102301](https://user-images.githubusercontent.com/12943935/94465462-c8b3e900-0174-11eb-8896-fd2bdd6c8468.png)
![Ligerzero_2020 09 28_101543](https://user-images.githubusercontent.com/12943935/94465498-d9fcf580-0174-11eb-9591-941c7d348587.png)

**Comment by EpicTaru** [comment]
Verified deletion/addition of any KIs that needed to be done and adjustment of the MissionStatus/any other variables necessary according to the code for completion of the battle. Congrats!
