### ISSUE TITLE
Rank 2-3 Workaround

### ISSUE THREAD

**Issue by glockfox** [HomepointXI/Issues#464]
**Date & Time**:  5:24pm 10/10/2020

**Client Version (use `/ver` in game): 30200904_2 **

**Character Name: Glockfox **

**Discord Name (if different from in game):**

**Nation:Bastok **

**Job(level)/Sub Job(level):63/31**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection): no**

**Steps to reproduce: attempt to start the battle**

**Any additional information: stuck in the starting battle dialogue**

**Comment by EpicTaru** [comment]
Which battlefield are you doing the battle at?

**Comment by glockfox** [comment]
Balgas Dias is the battlefield

**Comment by EpicTaru** [comment]
The version mismatch between the server version and your client version caused the CS to freeze. I'll force you thru the CS you're  frozen in. The forcing of you thru the CS will cause your camera to be frozen at the entrance to the battlefield for the battle and because of that, I'm only requiring a defeat of one of the two mobs in the battle (more power to you if you manage to defeat both, lol).

**You need to screenshot the message of you defeating one of the two mobs and then add that screenshot to this ticket** (you can then either die or leave the battle) and I'll fix your variables to be as if you completed the battle successfully. You'll be able to continue the rest of the 2-3 mission storyline to complete it and obtain Rank 3.

I'll verify that your variables and whatnot are correct after you've completed the battle to allow you to progress onward.

Knowing all this, are all of your characters ready to enter the battle? Please respond here.

**Comment by glockfox** [comment]
yes please!

**Comment by glockfox** [comment]
thank you very much!!!

**Comment by EpicTaru** [comment]
Verified deletion/addition of any KIs that needed to be done and adjustment of the MissionStatus/any other variables necessary according to the code for completion of the battle. Congrats!
