### ISSUE TITLE
Missing ??? for Detonator Weaponskill NM spawn

### ISSUE THREAD

**Issue by PunchdrunkXI** [HomepointXI/Issues#482]
**Date & Time**: 14th December 2020. 3.30PM

**Client Version (use `/ver` in game):**30200604_0

**Character Name:**Buffdrunk

**Discord Name (if different from in game):**Punchdrunk

**Nation:**Bastok

**Job(level)/Sub Job(level):**COR99/DNC49

**NPC or Monster or item Name:**Beet Leafhopper

**Zone name:** The Boyahda Tree

**Coordinates (use `!where`):**X-12 Y-19 Z-179 (240)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**Yes

**Steps to reproduce:**

**Any additional information:**

**Comment by EpicTaru** [comment]
Verified that the player has the necessary key item **MAP_TO_THE_ANNALS_OF_TRUTH** (KI ID 344).

Basecode line in the npc_list.sql file has the value incorrect for the QM related to the ???:
INSERT INTO `npc_list` VALUES (17404356,'qm1','???',0,0.000,0.000,0.000,0,50,50,0,0,0,**2**,3,0x0000320000000000000000000000000000000000,0,NULL,1);

should be:
INSERT INTO `npc_list` VALUES (17404356,'qm1','???',0,0.000,0.000,0.000,0,50,50,0,0,0,**0**,3,0x0000320000000000000000000000000000000000,0,NULL,1);

The 2 value means that the status is **HIDDEN**, it should be a 0 value which means that the status is **NORMAL**

Force-spawned the WSNM (Mob ID **17404338**) so that the player could proceed with the WS quest.

Leaving this issue open for issues with any of the other WSNM quests that this player or any other player may have.

**Comment by PunchdrunkXI** [comment]
![Buffdrunk_2020 12 14_154425](https://user-images.githubusercontent.com/68868049/102102258-7ef9a700-3e23-11eb-91ec-a66603e77ad3.png)

**Comment by EpicTaru** [comment]
Gave character Key Item **ANNALS_OF_TRUTH** (KI ID 345) so they are able to continue on with the WS quest. Congrats!

**Comment by PunchdrunkXI** [comment]
Mission accomplished! Was able to finish quest. thanks again ET /cheer

**Comment by EpicTaru** [comment]
NPNP, always happy to assist.  Congrats!

Leaving this issue open for issues with any of the other WSNM quests that this player or any other player may have.

**Comment by neoffxi** [comment]
Date & Time: 14th December 2020. 3.30PM

**Client Version (use /ver in game):**30200604_0

**Character Name:**Neoseventeen

**Discord Name (if different from in game):**NeoArmy

**Nation:**Bastok

**Job(level)/Sub Job(level):**COR99/DNC49

**NPC or Monster or item Name:**Beet Leafhopper

Zone name: The Boyahda Tree

**Coordinates (use !where):**X-12 Y-19 Z-179 (240)

Item tool link (for items issues only):

**Multi-boxing? (multiple clients on same connection):**Yes

Steps to reproduce:
The same issue as the listing above. The ??? to pop the NM is missing.

Any additional information:

**Comment by EpicTaru** [comment]
@neoffxi Please head to where the ??? would normally be at in The Boyahda Tree and we'll take care of the issue for you.

**Comment by EpicTaru** [comment]
Force-spawned the WSNM (Mob ID **17404338**) so that the player could proceed with the WS quest.

Please provide a screenshot of the death message of the NM so that I can give you the KI that you would normally obtain by checking the (currently non-existent) ??? after defeating the WSNM).

**Comment by neoffxi** [comment]
![Untitled](https://user-images.githubusercontent.com/34224364/115155248-00b94580-a04d-11eb-950e-641de357a66b.png)

**Comment by neoffxi** [comment]
Thanks ET

**Comment by EpicTaru** [comment]
Gave character Key Item **ANNALS_OF_TRUTH** (KI ID 345) so they are able to continue on with the WS quest.

NPNP, always happy to assist.  Congrats!

Leaving this issue open for issues with any of the other WSNM quests that this player or any other player may have.

**Comment by EpicTaru** [comment]
Fixed in update on 04/29/2021.  Closing ticket.
