### ISSUE TITLE
Dynamis Xarcabard item drop issues

### ISSUE THREAD

**Issue by Dankykong** [HomepointXI/Issues#493]
**Date & Time**: 
Jan 21, 2021 2PM EST

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Vixxen

**Discord Name (if different from in game):**
Sevvghetto

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
99THF/49DNC

**NPC or Monster or item Name:**
Vanguard Dragon and Satalite Dagger

**Zone name:** 
Dynamis Xarcabard

**Coordinates (use `!where`):**
X: 232, Y: -21.238, Z: -170
X: -185.895, Y: -3.083, Z: -4.321

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
no

**Steps to reproduce:**

**Any additional information:**
Daggers aren't dropping pop item and I can't find the dragons

**Comment by EpicTaru** [comment]
The satellite weapons don't have the pop item coded in their drop lists that are now used to force spawn the animated weapon of the same type.

Since there is so much fun that the workarounds for all of the prior Dynamis zones provided, especially Dynamis - Jeuno and Dynamis - Beaucedine, until the above issue with the satellite weapons is resolved, in order for me to force spawn the relevant Animated Weapon of the same type, the following is the requirement:

Locate and defeat all 6 of the Satellite Weapons of the same type as the Animated Weapon. Please screenshot the death messages of the Satellite Weapons and paste the screenshots here. I will then force spawn the relevant Animated Weapon of that type.

The Item Tool shows the Necropsyche correctly dropping from the Vanguard Dragons on the ramps near the zone to where Castle Z is. This is all well and good except that the Vanguard Dragons are set in the code as scripted spawns but there currently is no supporting code that actually spawns them. After you provide the screenshots of the death messages of the satellite weapons, I will also force spawn all of the Vanguard Dragons.

**Comment by Dankykong** [comment]
![x1](https://user-images.githubusercontent.com/77759083/105413378-42278980-5bf3-11eb-8df8-5b6537c244b3.png)
![x2](https://user-images.githubusercontent.com/77759083/105413385-43f14d00-5bf3-11eb-8f22-92513db6fba8.png)
![x3](https://user-images.githubusercontent.com/77759083/105413389-45227a00-5bf3-11eb-851f-9cd42a5a854b.png)
![x4](https://user-images.githubusercontent.com/77759083/105413401-46ec3d80-5bf3-11eb-867f-d18e9716a8af.png)
![x5](https://user-images.githubusercontent.com/77759083/105413407-48b60100-5bf3-11eb-8019-e8b3038dc89f.png)
![x6](https://user-images.githubusercontent.com/77759083/105413412-4a7fc480-5bf3-11eb-8e52-58303d32de8e.png)

**Comment by EpicTaru** [comment]
Good work on defeating all 6!  I'm waiting at the pop spot of the relevant Animated Weapon, I'll spawn it when you are there.  I'll also spawn the Vanguard Dragons so you can go hunt those down after you're done with the Animated Weapon.

**Comment by Dankykong** [comment]
Got both drops on first kills. Requirements were fun and easy!

**Comment by EpicTaru** [comment]
Leaving this issue open for any other player that also encounters this.

**Comment by EpicTaru** [comment]
Fixed in update on 04/29/2021.  Closing ticket.
