### ISSUE TITLE
Divine Might, characters between two owners teleported to different battlefield.

### ISSUE THREAD

**Issue by tuing** [HomepointXI/Issues#511]
Date & Time:
04/21/2021 @ 08:00 AM

Client Version (use /ver in game):
30191204_1

Character Name:
Minimey
Higuchi
Belledonna (Vixxen's alt)

Discord Name (if different from in game):
Meyrink
Sevvghetto (Vixxen)

Nation:
Sandoria
Sandoria
Bastok 

Job(level)/Sub Job(level):
99 WHM/49 RDM
99 BRD/ 49 WHM
99 WAR/49 DNC

NPC or Monster or item Name:
AA GK TT HM MR EV

Zone name:
Laloff Amphitheatre

Coordinates (use !where):
forgot to take note again...

Item tool link (for items issues only):
n/a

Multi-boxing? (multiple clients on same connection):
Yes

Steps to reproduce:
Vixxen the owner of character of Omobolasire and Belledonna traded the Ark Pentasphere even though Vixxen herself already did it in the past. Afterwards Vixxen got teleported to BC that got proper all 5 Ark Angels. Meanwhile Meyrink (helper as well), Minimey, Higuchi, Omobolasire, and Belledonna teleported to different battlefield that also have their own 5 Ark Angels. We proceeded to kill it where in the end only Omobolasire the one got clearance cs whereas the other didn't.

Attached logs of each AA death on the BC:
![EV](https://user-images.githubusercontent.com/26522986/115483360-d947c000-a27a-11eb-9f9d-04b31afe3442.png)
![GK](https://user-images.githubusercontent.com/26522986/115483369-da78ed00-a27a-11eb-93e6-a1ec759d8ced.png)
![HM](https://user-images.githubusercontent.com/26522986/115483372-db118380-a27a-11eb-8d3c-b800f445302d.png)
![MR](https://user-images.githubusercontent.com/26522986/115483374-dbaa1a00-a27a-11eb-8f0d-e3c04d3a5c7e.png)
![TT](https://user-images.githubusercontent.com/26522986/115483378-dc42b080-a27a-11eb-8041-ab57893a2b24.png)

**Comment by EpicTaru** [comment]
Since character Omobolasire received the ending cutscene their variables updated correctly and no adjustment of that character's variables was necessary.

For the remaining characters that needed the win status of this battle (Higuchi, Minimey, Belledonna), the following verifications occurred:

Verified that Outlands quest DIVINE_MIGHT has a value of ACCEPTED (!checkquest 5 163)

Verified that current Zilart Mission has a value of 26 to indicate that they are on ARK_ANGELS (!checkmission 3)

Higuchi and Minimey had already completed Zilart Mission ARK_ANGELS separately so adjustment of the their variables related to that was not necessary (indicated below with *).

Once these verifications occurred, the following actions were then done:

Force-completed quest DIVINE_MIGHT (!completequest 5 163)

Force-completed Zilart Mission ARK_ANGELS (!completemission 3 26)*

Force-added Zilart Mission THE_SEALED_SHRINE (!addmission 3 27)*

Checked that variable DivineMight had a value of 2 (!checkvar DivineMight) or set it to reflect that (!setplayervar DivineMight 2)

The following KIs were added to the characters that had not already completed Zilart Mission ARK_ANGELS:
SHARD_OF_APATHY (KI ID 455),*
SHARD_OF_ARROGANCE (KI ID 456),*
SHARD_OF_COWARDICE (KI ID 457),*
SHARD_OF_ENVY (KI ID 458),*
SHARD_OF_RAGE (KI ID 459),*

For the characters that had not already completed Zilart Mission ARK_ANGELS, checked that variable ZilartStatus had a value of 0 (!checkvar ZilartStatus) or set it to reflect that (!setplayervar ZilartStatus 0)*

Keeping this issue open for any other players that may also experience it in the future.

**Comment by EpicTaru** [comment]
fixed in upcoming update!

**Comment by EpicTaru** [comment]
This issue was resolved in yesterday's maintenance. Please open a new ticket should this issue re-occur.
