### ISSUE TITLE
Field of Valor Book Incorrect Text

### ISSUE THREAD

**Issue by ZurmaFFXI** [HomepointXI/Issues#550]
**Date & Time**: 
August 22nd, 2021 - 11:19am EST

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Zurma

**Discord Name (if different from in game):**

**Nation:**
Windurst (The Best of Vana'diel)

**Job(level)/Sub Job(level):**
19 Monk

**NPC or Monster or item Name:**
Neither of those

**Zone name:** 
Tahrongi Canyon

**Coordinates (use `!where`):**
X:317 Y:-16 Z:-87 (101)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
Double clicked the Field of Valor book
Selected Page 5
Accepted Page 5

**Any additional information:**
![Book Error1](https://user-images.githubusercontent.com/89349557/130360722-70f127cd-bb01-4a8f-b968-1d1b72ba309e.png)

**Comment by EpicTaru** [comment]
Issue presents itself regardless of page selected.

**Comment by EpicTaru** [comment]
Checked all other zones with a field manual or grounds tome in it. Issue also exists with the Field Manuals in The Sanctuary of Zi'Tah (Zone 121).  No zones with Grounds Tomes have the issue.

**Comment by Heepster03** [comment]
Fixed for next update!

**Comment by EpicTaru** [comment]
![image](https://user-images.githubusercontent.com/26195580/136260115-6913e641-a265-4e22-8256-964e67a7afa7.png)

![image](https://user-images.githubusercontent.com/26195580/136260449-4bcfb1b2-6d88-47af-9362-bfc170f5fb10.png)

This issue was resolved in yesterday's maintenance. Please open a new ticket should this issue re-occur.
