### ISSUE TITLE
Missing Item Mods: Sancus Sachet/Arasy Sachet

### ISSUE THREAD

**Issue by protocolz2025** [HomepointXI/Issues#565]
**Date & Time**: 
2021/10/10

**Client Version (use `/ver` in game):**

**Character Name:**

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**
Maybe everyone knows this but let me point out.

Unknown Mod (541) 6
(25): Accuracy +15
(26): Ranged Accuracy +15
(30): Magic Accuracy +15
Unknown Mod (126) 10

-----------------------------
And here's what people are expecting.

"Blood Pact" recast time II -6 
Avatar: Lv119 
"Blood Pact" damage +10 
Accuracy+15 Ranged Accuracy+15 Magic Accuracy+15

https://www.bg-wiki.com/ffxi/Sancus_Sachet

Arasy Sachet should have the same "Avatar: Lv119 "  but it's also missing.

**Any additional information:**

**Comment by EpicTaru** [comment]
http://wiki.homepointxi.com/Arasy_Sachet regarding that sachet.

**Comment by Heepster03** [comment]
![image](https://user-images.githubusercontent.com/8421725/136678276-3302cfb1-08e2-4e59-9450-2fd8b329e4b4.png)

![image](https://user-images.githubusercontent.com/8421725/136678269-5d60b219-a883-4e06-b822-b3605398598b.png)

Also our custom is set here you put your pet level to whatever your level weapon you have equipped. So, if you have a 119 weapon, you have a 119 pet. Therefore due to how the custom works here, everything is working as intended.
