### ISSUE TITLE
Unable to change nation Bastok -> Sand'oria

### ISSUE THREAD

**Issue by Suikodenxi** [HomepointXI/Issues#615]
**Date & Time**: 
01/23/2023 11:15AM PST

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Redheadman

**Discord Name (if different from in game):**

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
99WAR/49DRG

**NPC or Monster or item Name:**
Rashid

**Zone name:** 
Bastok mines

**Coordinates (use `!where`):**
X:-8 Y:-1 Z:-122 (78)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**
Rank 10 Bastok trying to immigrate to Sand'oria but the immigration NPC says He cannot accept application from me and the Bastok mission giver is trying to give repeatable missions.

**Any additional information:**

**Comment by EpicTaru** [comment]
@Suikodenxi What does Beriphaule in North Sandy at C-9 say to you when you speak to them about changing nation?

Were you trying to change nations on more than one character at once?

Also, when you interacted with Iron Eater in Metalworks for the completion of Bastok 9-2, did you interact with more than one character at once?

**Comment by Suikodenxi** [comment]
1. Beriphaule says: "I cannot accept applications for San d'orian citizenship while you are on a mission."
2. Yes the other 5 characters immigrated successfully.
3. yes

**Comment by EpicTaru** [comment]
OK, so your **MissionStatus** variable currently has a value of **2**, that variable has to have a value of **255** or **0** in order for Beriphaule to proceed with the immigration process. 

That variable should have been set to **0** by Iron Eater at the end of Bastok 9-2 but it wasn't set for whatever reason, may have been due to you interacting with Iron Eater for the mission completion on multiple characters at once.

The value of the **MissionStatus** variable has now been set to the correct value of **0**.

Please attempt to interact with Beriphaule again and see if the immigration process goes thru without any issues.  

Please report back here with your findings of this attempt, regardless of the outcome.  Do not close this ticket, I will close it after you report back with your findings.

**Comment by Suikodenxi** [comment]
Okay Beriphaule now accepts my application.
Thank you.^^
